### ISSUE TITLE
Create linting workflows

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai-api#47]
Add linting to this repository.

```[tasklist]
### Tasks
- [ ] Create a workflow that uses [ChartBoost/ruff-action](https://github.com/ChartBoost/ruff-action) to validate PRs
- [ ] Create a pre-commit hook that runs [https://github.com/astral-sh/ruff?tab=readme-ov-file](https://github.com/astral-sh/ruff?tab=readme-ov-file) locally.
- [ ] Create workflow (or add to prior workflow) to lint zarf packages with zarf prepare lint
```
